spring:
  profiles:
    active:
      - dev

---

spring:
  config:
    activate:
      on-profile: dev   # 开发环境
  application:
    name: lwohvye-springcloud-config-dev

---

spring:
  config:
    activate:
      on-profile: prod   # 生产环境
  application:
    name: lwohvye-springcloud-config-prod
