spring:
  profiles:
    active:
      - dev

config:
  info: "version=2020-01-update-merge"

---
server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

feign:
  hystrix:
    enabled: true

spring:
  profiles: dev
  redis:
    database: 0
    host: 192.168.0.145
    lettuce:
      pool:
        max-active: 10
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: redis
    port: 6380
    timeout: 1000

swagger:
  enable: true