spring:
  profiles:
    active:
      - dev

---
server:
  http2:
    enabled: true
  port: 8084
  undertow:
    direct-buffers: true
    io-threads: 6
    worker-threads: 48

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: lwohvye-provider-8084
    prefer-ip-address: true

info:
  app:
    name: spring-cloud-lwohvye
  build:
    artifactId: $project.artifactId$
    version: $project.version$

logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: lwohvye-provider
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jmx:
    enabled: false
    profiles: dev
    
  rabbitmq: #rabbitmq相关配置，15672是web管理端口，5672是mq访问端口
    port: 5672
    host: 10.211.55.140
    username: admin
    password: admin
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
