spring:
  profiles:
    active:
      - dev

---
server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/

spring:
  rabbitmq: #rabbitmq相关配置，15672是web管理端口，5672是mq访问端口
    port: 5672
    host: 10.211.55.140
    username: admin
    password: admin
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 10
#             default并未作用到声明的instance，未声明的反而有效果，应该是有部分规则还不清楚
    instances:
        swarm:
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 25s
            failureRateThreshold: 50
            slowCallRateThreshold: 80
            slowCallDurationThreshold: 2s
