
spring:
  profiles:
    active:
      - dev

---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: lwohvye-springcloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    instance:
      instance-id: lwohvye-spring-cloud-config-client-8201
        prefer-ip-address: true     #访问路径可以显示IP地址
---
server:
  port: 8202

spring:
  profiles: prod
  application:
    name: lwohvye-springcloud-config-client.yml

eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
    instance:
      instance-id: lwohvye-spring-cloud-config-client-8202
        prefer-ip-address: true     #访问路