spring:
  profiles:
    active:
      - dev

config:
  info: "version=2020-01-update-merge"

---
server:
  http2:
    enabled: true
  port: 8084
  undertow:
    direct-buffers: true
    io-threads: 6
    worker-threads: 48

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: lwohvye-provider-8084
    prefer-ip-address: true

info:
  app:
    name: spring-cloud-lwohvye
  build:
    artifactId: $project.artifactId$
    version: $project.version$

logging:
  config: classpath:logback-spring.xml
  level:
    com:
      lwohvye:
        springcloud:
          springcloudlwohvyeprovider:
            dao: debug

spring:
  application:
    name: lwohvye-provider
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jmx:
    enabled: false
    profiles: dev
