
spring:
  profiles:
    active:
      - dev

config:
  info: "version=2020-01"

---
server:
  port: 8201

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: lwohvye-springcloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: lwohvye-spring-cloud-config-client-8201
    prefer-ip-address: true     #访问路径可以显示IP地址

---
server:
  port: 8202

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: lwohvye-springcloud-config-client.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: lwohvye-spring-cloud-config-client-8202
    prefer-ip-address: true     #访问路
