spring:
  profiles:
    active:
      - dev

---
server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/

spring:
  rabbitmq: #rabbitmq相关配置，15672是web管理端口，5672是mq访问端口
    port: 5672
    host: 10.211.55.140
    username: admin
    password: admin
    
management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.circuitbreaker:
#     configs可指定多个，在instances中通过 baseConfig引入
    configs:
#     default会覆盖默认值，但对声明的instance不生效，需在其中显示指定，对未声明的instance是生效的
        default:
            registerHealthIndicator: true
            slidingWindowSize: 10
    instances:
        swarm:
            baseConfig: default
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 25s
            failureRateThreshold: 50
            slowCallRateThreshold: 80
            slowCallDurationThreshold: 2s
